---
- name: "Create, Update or Delete S3 Bucket {{ bucket_name }}."
  cloudformation:
    profile: "{{ profile }}"
    aws_region: "{{ region }}"
    disable_rollback: false
    stack_name: "{{ cf_stack_names.s3_bucket_stack_name }}-{{ bucket_name }}"
    state: present
    create_changeset: false
    tags:
      Name: "{{ cf_stack_names.s3_bucket_stack_name }}-{{ bucket_name }}"
    template: "cf-templates/s3.yml"
    template_parameters: "{{ bucket_parameters[bucket_name]['cf_params'] }}"
  register: s3_bucket_stack_results
